# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            flagbug
tagline:          ''
description:      ''
url:              http://flagbug.com

paginate:         5